name: Django Staging Deploy
on:
  push:
    branches: [staging]
jobs:
  deploy:
    runs-on: ubuntu-version-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput
    - name: Apply Database Migrations
      run: |
        python manage.py migrate
    - name: Start Application
      run: |
        python manage.py runserver